[package]
name = "select_demo"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
native-windows-derive2 = {path = "../../../native-windows-derive2"}
native-windows-gui2 = {path = "../../"}
